stages:
    - "build"
    - "test"
    - "deploy"

image : docker
build-image:
  stage: build
  services:
    - docker:dind
  before_script:
    - echo "${DOCKERHUB_PWD}" | docker login -u "${DOCKERHUB_USER}" --password-stdin
  script:
    - docker build -t $IMAGE_TAG .
    - echo "docker build finished"
    - docker push $IMAGE_TAG
    - echo "docker push finished"

test:
  stage: test
  dependencies:
    - "build-image"
  script:
    - nunit-console PuYuanTests.dll
    - echo "NUnit test..."

deploy-job: 
  stage: deploy     
  dependencies:
    - "test"
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
