stages:
    - "build"
    - "test"
    - "deploy"

# image : docker
# build-image:
#   stage: build
#   services:
#     - docker:dind
#   before_script:
#     - echo "${DOCKERHUB_PWD}" | docker login -u "${DOCKERHUB_USER}" --password-stdin
#   script:
#     # - docker build -t $IMAGE_TAG .
#     - echo "docker build finished"
#     # - docker push $IMAGE_TAG
#     - echo "docker push finished"

test:
  # image: rschmitz/nunit3-console
  image: bitnami/dotnet-sdk:latest
  stage: test
  # dependencies:
  #   - "build-image"
  # before_script:
  #   - 'CHCP 65001'
  script:
    - echo "dotnet restore..."
    - dotnet restore
    - cd PuYuanTests
    - echo "dotnet test..."
    - dotnet test PuYuanTests.csproj --no-build --logger:"nunit;LogFileName=test-run.xml"
    # - 'nuget restore PuYuan.sln'
    # - 'msbuild "PuYuan.sln"'
    # - 'set NUNIT_CONSOLE=%USERPROFILE%\.nuget\packages\nunit.consolerunner\3.15.2\tools\nunit3-console.exe'
    # - 'set PUYUANTESTS_PATH=PuYuanTests\bin\Debug\net6.0\PuYuanTests.dll'
    # - '"%NUNIT_CONSOLE%" "PUYUANTESTS_PATH"'
    # - '"%NUNIT_CONSOLE%" "PuYuanTests.dll" --config=Release --work=.\TestResult --result=TestResult.xml --result=junit-results.xml;transform=nunit3-junit.xslt'
  artifacts:
    when: always
    paths:
      - TestResult/test-run.xml
      # - TestResult/junit-results.xml
      # - TestResult/TestResult.xml
  #   reports:
  #     junit: TestResult/junit-results.xml


# deploy-job: 
#   stage: deploy     
#   dependencies:
#     - "test"
#   script:
#     - echo "Deploying application..."
#     - echo "Application successfully deployed."
