stages:
    - "build"
    - "test"
    - "deploy"

# image : docker
# build-image:
#   stage: build
#   services:
#     - docker:dind
#   before_script:
#     - echo "${DOCKERHUB_PWD}" | docker login -u "${DOCKERHUB_USER}" --password-stdin
#   script:
#     # - docker build -t $IMAGE_TAG .
#     - echo "docker build finished"
#     # - docker push $IMAGE_TAG
#     - echo "docker push finished"

test:
  image: bash:latest
  stage: test
  # dependencies:
  #   - "build-image"
  # before_script:
  #   - 'CHCP 65001'
  script:
    - 'set NUNIT_CONSOLE=%USERPROFILE%\.nuget\packages\nunit.consolerunner\3.15.2\tools\nunit3-console.exe'
    - '"%NUNIT_CONSOLE%" "PuYuanTests.dll" --config=Release --work=.\TestResult --result=TestResult.xml --result=junit-results.xml;transform=nunit3-junit.xslt'
  artifacts:
    when: always
    paths:
      - TestResult/junit-results.xml
      - TestResult/TestResult.xml
    reports:
      junit: TestResult/junit-results.xml


# deploy-job: 
#   stage: deploy     
#   dependencies:
#     - "test"
#   script:
#     - echo "Deploying application..."
#     - echo "Application successfully deployed."
