# stages:
#     - "build"
    # - "test"
    # - "deploy"
image : docker
build-image:
  # stage: build
  # services:
  #   - docker:dind
  # tags:
  #   - shell
  script:
    - echo "docker build"
    #- docker build -t puyuantestimage .

# test:
#   stage: test
#   dependencies:
#     - "build-image"
#   script:
#     - echo "test.

# deploy-job: 
#   stage: deploy     
#   dependencies:
#     - "test"
#   script:
#     - echo "Deploying application..."
#     - echo "Application successfully deployed."
