version: "3.9"

services:
  mssql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    hostname: "mssql"
    restart: always
    ports: 
        - 1433:1433
    environment:
      - ACCEPT_EULA="Y"
      - SA_PASSWORD=98a0bc92-2106-488b-9641-b4fe2a13657d
